---
date-modified: last-modified
draft: true
categories: [open science, FAIR]
---

The FAIR Data Principles were created as guidelines to
making data more reusable, both by humans and machines.
FAIR stands for Findable, Accessible, Interoperable, and
Reusable.

Findable means you can actually locate the data. This
requires the data to be assigned a persistent identifier (PID).
The data should be accompanied by metadata, which are
registered in a searchable resource.

Accessible means there should be a clear path to accessing
the data. Preferably an open, standardised protocol. Access
can be restricted, if necessary.

Interoperable means the data should be in a format that allows
them to be used in common applications and workflows, preferably
an open source format. The metadata for assets should also use
agreed-upon community standards.

Reusable means the data should be well-documented. This includes
domain-relevant guidance for researchers who wish to reuse the
data, and a provenance of their creation. A license should be
used to indicate the terms of reuse, such as a
[creative commons](https://creativecommons.org/) license.
